channels:
- conda-forge
dependencies:
- python=3.9.18
- pip<=23.0.1
- pip:
  - mlflow==2.11.3
  - cloudpickle==2.2.1
  - numpy==1.22.3
  - packaging==23.2
  - pandas==2.0.2
  - psutil==5.9.6
  - pyyaml==6.0.1
  - scikit-learn==1.3.0
  - scipy==1.10.1
  - xgboost==2.0.0
name: mlflow-env
