channels:
- conda-forge
dependencies:
- python=3.9.19
- pip<=23.3.1
- pip:
  - mlflow==2.11.3
  - cloudpickle==2.2.1
  - importlib-metadata==7.0.1
  - lz4==4.3.2
  - numpy==1.22.4
  - packaging==23.2
  - pandas==2.1.4
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.3.0
  - scipy==1.12.0
  - xgboost==2.0.3
name: mlflow-env
